//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoWebForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MermaidHelp.Pages
{
	public partial class IndexModel
	{
		protected FineUICore.Panel mainPanel;
		protected FineUICore.Panel leftPanel;
		protected FineUICore.Panel codePanel;
		protected FineUICore.Panel textPanel;
		protected FineUICore.Panel messagePanel;
		protected FineUICore.TextArea txtInput;
		protected FineUICore.Panel rightPanel;
	}
}
